import { prisma } from "@/lib/prisma";

const INGREDIENTS = [
  // Bases
  "Té Negro",
  "Té Verde",
  "Té Blanco",
  "Té Rojo (Pu Erh)",
  "Té Oolong (Azul)",
  "Té Matcha",
  "Rooibos",
  "Honeybush",
  "Yerba Mate",
  "Tulsi",

  // Especias
  "Canela",
  "Jengibre",
  "Cardamomo",
  "Clavo",
  "Pimienta negra",
  "Pimienta rosa",
  "Pimienta blanca",
  "Anís estrellado",
  "Anís verde",
  "Nuez moscada",

  //Hierbas y Plantas
  "Hinojo",
  "Regaliz",
  "Vainilla",
  "Menta",
  "Hierbabuena",
  "Hierba limón (Lemongrass)",
  "Hierbaluisa",
  "Melisa",
  "Cúrcuma",
  "Chile",
  "Cilantro",
  "Ortiga",
  "Valeriana",
  "Tila",
  "Salvia",
  "Tomillo",
  "Romero",
  "Eucalipto",
  "Ginseng",
  "Ginkgo Biloba",
  "Moringa",
  "Estevia",
  "Olivo",
  "Bambú",

  // Cítricos
  "Cáscara de naranja",
  "Cáscara de limón",
  "Lima",
  "Naranja",
  "Limón",
  "Bergamota",
  "Pomelo",
  "Mandarina",
  "Flor de Azahar",
  "Yuzu",

  // Frutas
  "Manzana",
  "Fresa",
  "Frambuesa",
  "Arándano",
  "Grosella",
  "Cereza",
  "Melocotón",
  "Albaricoque",
  "Mango",
  "Piña",
  "Papaya",
  "Coco",
  "Higo",
  "Dátil",
  "Pasas",
  "Fruta de la pasión",
  "Plátano",
  "Bayas de Goji",
  "Saúco",
  "Escaramujo",
  "Pera",
  "Maracuyá",
  "Melón",
  "Sandía",
  "Mora",
  "Ciruela",
  "Granada",
  "Kiwi",

  // Flores
  "Pétalos de rosa",
  "Hibisco",
  "Lavanda",
  "Jazmín",
  "Azahar",
  "Manzanilla",
  "Aciano (Flor de aciano)",
  "Caléndula",
  "Malva",
  "Girasol",
  "Violeta",
  "Azafrán silvestre",
  "Osmanthus",
  "Sauco",
  "Peonía",
  "Crisantemo",

  // Dulces y Gourmand
  "Cacao",
  "Cáscara de cacao",
  "Chocolate",
  "Chocolate blanco",
  "Caramelo",
  "Toffee",
  "Nubes de azúcar (Marshmallows)",
  "Turrón",
  "Almendra",
  "Nuez",
  "Avellana",
  "Pistacho",
  "Nuez de Macadamia",
  "Miel",
  "Yogur",
  "Nata",
  "Sirope de arce",
  "Piñones",
  "Dulce de leche",
  "Galleta",

  // Otros
  "Zanahoria",
  "Remolacha",
  "Calabaza",
  "Arroz tostado (Genmaicha)",
  "Algas",
  "Hojas de zarzamora",
];

export async function seedIngredients() {
  for (const name of INGREDIENTS) {
    await prisma.teaIngredient.upsert({
      where: { name },
      create: { name },
      update: {},
    });
  }
}

seedIngredients()